/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemHealthRouteImport } from './routes/system-health'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrintersRouteImport } from './routes/printers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AlertCenterRouteImport } from './routes/alert-center'
import { Route as IndexRouteImport } from './routes/index'

const SystemHealthRoute = SystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintersRoute = PrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertCenterRoute = AlertCenterRouteImport.update({
  id: '/alert-center',
  path: '/alert-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert-center': typeof AlertCenterRoute
  '/alerts': typeof AlertsRoute
  '/login': typeof LoginRoute
  '/printers': typeof PrintersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert-center': typeof AlertCenterRoute
  '/alerts': typeof AlertsRoute
  '/login': typeof LoginRoute
  '/printers': typeof PrintersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert-center': typeof AlertCenterRoute
  '/alerts': typeof AlertsRoute
  '/login': typeof LoginRoute
  '/printers': typeof PrintersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/system-health': typeof SystemHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert-center'
    | '/alerts'
    | '/login'
    | '/printers'
    | '/reports'
    | '/settings'
    | '/system-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert-center'
    | '/alerts'
    | '/login'
    | '/printers'
    | '/reports'
    | '/settings'
    | '/system-health'
  id:
    | '__root__'
    | '/'
    | '/alert-center'
    | '/alerts'
    | '/login'
    | '/printers'
    | '/reports'
    | '/settings'
    | '/system-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertCenterRoute: typeof AlertCenterRoute
  AlertsRoute: typeof AlertsRoute
  LoginRoute: typeof LoginRoute
  PrintersRoute: typeof PrintersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SystemHealthRoute: typeof SystemHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/system-health': {
      id: '/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof SystemHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printers': {
      id: '/printers'
      path: '/printers'
      fullPath: '/printers'
      preLoaderRoute: typeof PrintersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-center': {
      id: '/alert-center'
      path: '/alert-center'
      fullPath: '/alert-center'
      preLoaderRoute: typeof AlertCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertCenterRoute: AlertCenterRoute,
  AlertsRoute: AlertsRoute,
  LoginRoute: LoginRoute,
  PrintersRoute: PrintersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SystemHealthRoute: SystemHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
